blank_issues_enabled: false
contact_links:
  - name: Contributor Code of Conduct
    url: https://github.com/dailydotdev/awesome-developer-recruiting/blob/main/code-of-conduct.md
    about: Please review expected behavior before participating.
